### ISSUE TITLE
user can view a list of all characters in the game

### ISSUE THREAD

**Issue by byu014** [byu014/ajax-project#1]
## 📐 Functionality

user can view a list of all characters in the game

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/32401196/140989520-4a0c7b78-845a-4d9d-a201-461cda6db8fc.png)
![image](https://user-images.githubusercontent.com/32401196/140989608-9b997751-d01b-4dca-85ca-82d1055b4908.png)

## ✅ Task List

- [x] add background image and apply dark filter to it
- [x] add header with app name on left, nav items on right
- [x] create div with data-view="characters-view"
- [x] create heading that represents the current view
- [x] create template icon to match reference
- [x] using JS listen for 'DOMContentLoaded' to populate view with character icons using info from API
