### ISSUE TITLE
user can view information on selected character

### ISSUE THREAD

**Issue by byu014** [byu014/ajax-project#2]
## 📐 Functionality

user can view information on selected character

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/32401196/140989818-3d958d4b-52a3-4b23-975f-c2b0be7c4d24.png)
![image](https://user-images.githubusercontent.com/32401196/140989876-a00a18f0-307f-4f06-a5ed-e0b2f2bbce6c.png)

## ✅ Task List

- [x] create new view data-view="character"
- [x] allow heading to dynamically change to selected character's name and put its respsective element symbol next to it
- [x] create character portrait icon and add stars underneath it representing character's rarity
- [x] create white div and add character description
- [x] add character weapon type and element
- [x] add skills
