### ISSUE TITLE
user can view a list of all enemies in the game

### ISSUE THREAD

**Issue by byu014** [byu014/ajax-project#3]
## 📐 Functionality

user can view a list of all enemies in the game

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/32401196/140990095-f2bd87f9-50e7-4190-9121-2cae48ef09d3.png)
![image](https://user-images.githubusercontent.com/32401196/140990191-254725fd-5489-4d1b-8473-d6f4d10ae821.png)

## ✅ Task List

- [x] create view with data-view='enemies'
- [x] listen for clicks on nav for enemies and switch view to enemies when clicked
- [x] populate view with enemies loaded from api
