### ISSUE TITLE
user can view a list of all weapons in the game

### ISSUE THREAD

**Issue by byu014** [byu014/ajax-project#5]
## 📐 Functionality

user can view a list of all weapons in the game

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/32401196/140991348-bd382adc-6b3a-47aa-934c-a21ae6549512.png)

![image](https://user-images.githubusercontent.com/32401196/140990824-9c0ed5c6-9b49-42a6-964e-815d89a6ec83.png)

## ✅ Task List

- [x] create a new view data-view="weapons"
- [x] listen for clicks on nav for weapons and switch view to weapons when clicked
- [x] populate view with icons of weapons pulled from API, change weapon background color based on rarity
