### ISSUE TITLE
user can view information on selected weapon

### ISSUE THREAD

**Issue by byu014** [byu014/ajax-project#6]
## 📐 Functionality

user can view information on selected weapon

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/32401196/140990763-55c5ef5c-46c3-4339-9b40-87d833c8553c.png)
![image](https://user-images.githubusercontent.com/32401196/140991420-6156c2e1-a496-4384-874b-9ac1f5b255f0.png)

## ✅ Task List

- [x] add weapon portrait and rarity star rating
- [x] add white container with description
- [x] add weapon type and source information
- [x] add ascension materials
